apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app5
  labels:
    app: my-app5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app5
  template:
    metadata:
      labels:
        app: my-app5
    spec:
      containers:
      - name: udagram-api
        image: abythell74/udagram-api
        ports:
        - containerPort: 80
       
